spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          
  config:
    name: configserver
    
  profiles:
     active: native

server:
  port: 8888