FROM java:8-jre

MAINTAINER Tony Lopez <tony.lopez1013@gmail.com>

COPY ./target/employee-service-0.0.1-SNAPSHOT.jar /app/employee-service.jar

CMD ["java", "-jar", "/app/employee-service.jar"]

EXPOSE 9000